# ---
# # refs : https://docs.ansible.com/ansible/2.9_ja/galaxy/user_guide.html#requirements-yml

# # roles:
#   # Install a role from Ansible Galaxy.
#   # - name: geerlingguy.java
#   #   version: 1.9.6

# collections:
#   # https://galaxy.ansible.com/ui/repo/published/community/general/
#   - name: community.general
#     version: 7.5.0
#     source: https://galaxy.ansible.com
