version: '3.7'

services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.9.1
    volumes:
      - ./config/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    # 不用意にportが公開される・競合する可能性があるため、通常はnetwork mode host はあまり推奨しない。
    network_mode: host
    # ports:
    #   - 8200:8200
    hostname: apm-server
    # Elastic Agent does not retry failed connections to Kibana upon the initial enrollment phase.
    restart: on-failure

