---
- name: Ping Connection
  ansible.builtin.ping:

- name: "setting git config"
  become: true
  become_user: isucon
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: isucon
    - name: user.email
      value: isucon@isucon

# paramikoが必要でinstallが手間なので使わない
# - name: "setting ssh config"
#   become: true
#   become_user: isucon
#   vars:
#     ansible_python_interpreter: /usr/bin/python3
#   community.general.ssh_config:
#     host: "github.com"
#     identity_file: "~/.ssh/isugit2023"
#     hostname: "github.com"
#     user: isucon
#     strict_host_key_checking: false

- name: "setting ssh config"
  become: true
  become_user: isucon
  blockinfile:
    path: /home/isucon/.ssh/config
    create: true
    block: |
      Host github.com
        IdentityFile ~/.ssh/isugit2023
        User git
        HostName github.com
        StrictHostKeyChecking no


